---
title: "Unit tests workshop"
author: "Kamil Foltyński"
date: "03/04/2019"
output:
  html_document
runtime: shiny
---

Agenda:

* Intro
  * Clone repo:
    ```{bash,eval=FALSE}
    git clone git@github.com:Tazovsky/unit-tests-workshop.git
    ```
  * Instal helper R package:
    ```{r,eval=FALSE}
    devtools::install("unitTestsWorkshopPackage/")
    ```
* [Why do unit testing?](01-why-do-unit-testing.Rmd)
* [Correct R package structure](02-correct-structure.Rmd)
  * How to start if we don't have valid structure yet? `devtools::use_testthat()`
  * Common commands and shortcuts to run unit tests
    * Mention also about skipping tests, testing single files, whole dirs
  * Practical task
  * Test structure
    * `testthat` functions
* [Exceptions](03-exceptions.Rmd)
  * Why should we care?
  * Catching exceptions - examples
  * Testing exceptions
  * Practical task
* [Reference data](04-reference-data.Rmd)
* [How to test?](05-how-to-test.Rmd)
  * split big functionalities into separate test, e.g. 1st test connection to db, 2nd test function on prepared ref data from db
  * expect, expect, expect
  * code coverage
* [Test driven development](06-test-driven-development.Rmd)
  * What is that?
  * When to use - examples
* [R packages](r-packages.Rmd)

TODOs:

    