---
title: "Why do unit testing?"
author: "Kamil Foltyński"
date: "03/04/2019"
output:
  html_document:
    fig_caption: yes
    keep_md: no
    toc: yes
    toc_float:
      collapsed: no
      smooth_scroll: yes
runtime: shiny
---

```{r, echo=FALSE}
knitr::opts_chunk$set(collapse = TRUE, comment = ">")
```

# Why do unit testing?

1. Ensures implemented changes, improvements, fixes doen't break anything that already exists and works
    * Fixing specific feature may result in breaking some other functinality
2. Saves time and reduces costs
    * no need/reduced need for manual testing of code results
3. Makes refactoring much easier and faster and reduces risk
    * sometimes some old feature needs to be redesigned and changind already working and tested code is risky,
but when unit test are written it's much easier because we know what to expect, e.g. sepcific outputs 
4. With unit tests we get bonus: documentation :)
    * _documentation_, but not literally - what I mean is that when we look at unit tests code we can easily learn 
how some function or whole feature works, what input it accepts, what is the output, what _edge cases_ we can expect,
what we need to be careful of, etc.
5. Debug faster 
    * Well unit tested code is a boost in debugging - when last commit breaks test(s) it means last code change should be investigated. Without unit tests we might not even know that something was broken before last commit and 
it is just coincidence we noticed that now

# Sources

* https://dzone.com/articles/top-8-benefits-of-unit-testing



